server:
  port: 9997

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.31.0.67:3306/atom?useUnicode=true&character_set_server=utf8mb4&rewriteBatchedStatements=true
    username: root
    password: l8ka65
    max-idle: 10
    max-wait: 10000
    max-active: 200
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    filters: stat,wall,log4j
    min-evictable-idle-time-millis: 18800
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true