server:
  port: 9997

spring:
  redis:
    host: 172.31.0.219
    port: 6379
    password: unitymob
    pool:
      max-idle: 8
      min-idle: 1
      max-active: 8
      max-wait: -1
    timeout: 300000

  rabbitmq:
    host: 172.31.0.74
    port: 5672
    username: unitymob
    password: unitymob
    publisher-confirms: true
    virtual-host: unitymob
    connection-timeout: 300000
    cache:
      channel:
        checkout-timeout: 300000
    template:
      receive-timeout: 300000
      reply-timeout: 300000
    listener:
      simple:
        acknowledge-mode: none
        concurrency: 3
        max-concurrency: 3

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.31.0.67:3306/atom?useUnicode=true&character_set_server=utf8mb4&rewriteBatchedStatements=true
    username: root
    password: l8ka65
    max-idle: 10
    max-wait: 10000
    max-active: 200
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    filters: stat,wall,log4j
    min-evictable-idle-time-millis: 18800
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true